import { Tier } from './types';

export const TIERS: Record<string, Tier> = {
  gold: {
    id: 'gold',
    name: 'gold',
    displayName: 'Gold',
    benefits: [
      { id: 'gold-wine-1', label: '50% Off Glass of Wine/Beer/Soda (1/2)', type: 'per-sailing' },
      { id: 'gold-wine-2', label: '50% Off Glass of Wine/Beer/Soda (2/2)', type: 'per-sailing' },
      { id: 'gold-shake-1', label: '50% Off Johnny Rockets Milkshake (1/2)', type: 'per-sailing' },
      { id: 'gold-shake-2', label: '50% Off Johnny Rockets Milkshake (2/2)', type: 'per-sailing' },
      { id: 'gold-coffee', label: '25% Off Coffee', type: 'per-sailing' },
    ],
  },
  platinum: {
    id: 'platinum',
    name: 'platinum',
    displayName: 'Platinum',
    benefits: [
      { id: 'plat-wine-1', label: '50% Off Glass of Wine/Beer/Soda (1/2)', type: 'per-sailing' },
      { id: 'plat-wine-2', label: '50% Off Glass of Wine/Beer/Soda (2/2)', type: 'per-sailing' },
      { id: 'plat-shake-1', label: '50% Off Johnny Rockets Milkshake (1/2)', type: 'per-sailing' },
      { id: 'plat-shake-2', label: '50% Off Johnny Rockets Milkshake (2/2)', type: 'per-sailing' },
      { id: 'plat-coffee-1', label: '50% Off Coffee (1/2)', type: 'per-sailing' },
      { id: 'plat-coffee-2', label: '50% Off Coffee (2/2)', type: 'per-sailing' },
      { id: 'plat-laundry', label: '$5 Laundry Discount', type: 'per-sailing' },
      { id: 'plat-robes', label: 'Robes Requested', type: 'per-sailing' },
      { id: 'plat-casino', label: '$4 Casino FreePlay', type: 'per-sailing' },
    ],
  },
  emerald: {
    id: 'emerald',
    name: 'emerald',
    displayName: 'Emerald',
    benefits: [
      { id: 'em-wine-1', label: '50% Off Glass of Wine/Beer/Soda (1/2)', type: 'per-sailing' },
      { id: 'em-wine-2', label: '50% Off Glass of Wine/Beer/Soda (2/2)', type: 'per-sailing' },
      { id: 'em-shake-1', label: '50% Off Johnny Rockets Milkshake (1/2)', type: 'per-sailing' },
      { id: 'em-shake-2', label: '50% Off Johnny Rockets Milkshake (2/2)', type: 'per-sailing' },
      { id: 'em-coffee-1', label: '50% Off Coffee (1/2)', type: 'per-sailing' },
      { id: 'em-coffee-2', label: '50% Off Coffee (2/2)', type: 'per-sailing' },
      { id: 'em-laundry', label: '$5 Laundry Discount', type: 'per-sailing' },
      { id: 'em-robes', label: 'Robes Requested', type: 'per-sailing' },
      { id: 'em-casino', label: '$6 Casino FreePlay', type: 'per-sailing' },
      { id: 'em-waters', label: '2 Welcome Waters Received', type: 'per-sailing' },
      { id: 'em-bingo', label: '6 Free Bingo Cards', type: 'per-sailing' },
    ],
  },
  diamond: {
    id: 'diamond',
    name: 'diamond',
    displayName: 'Diamond',
    benefits: [
      { id: 'dia-drinks', label: 'Daily Drink Vouchers', type: 'daily', quantity: 4 },
      { id: 'dia-shake-1', label: '50% Off Johnny Rockets Milkshake (1/2)', type: 'per-sailing' },
      { id: 'dia-shake-2', label: '50% Off Johnny Rockets Milkshake (2/2)', type: 'per-sailing' },
      { id: 'dia-coffee-1', label: '50% Off Coffee (1/2)', type: 'per-sailing' },
      { id: 'dia-coffee-2', label: '50% Off Coffee (2/2)', type: 'per-sailing' },
      { id: 'dia-photo', label: '1 Free Photo', type: 'per-sailing' },
      { id: 'dia-internet', label: '1 Free Day Internet', type: 'per-sailing' },
      { id: 'dia-laundry', label: '$10 Laundry Discount', type: 'per-sailing' },
      { id: 'dia-robes', label: 'Robes Requested', type: 'per-sailing' },
      { id: 'dia-casino', label: '$6 Casino FreePlay', type: 'per-sailing' },
      { id: 'dia-waters', label: '2 Welcome Waters Received', type: 'per-sailing' },
      { id: 'dia-bingo', label: '6 Free Bingo Cards', type: 'per-sailing' },
    ],
  },
  'diamond-plus': {
    id: 'diamond-plus',
    name: 'diamond-plus',
    displayName: 'Diamond Plus',
    benefits: [
      { id: 'dp-drinks', label: 'Daily Drink Vouchers', type: 'daily', quantity: 5 },
      { id: 'dp-shake-1', label: '50% Off Johnny Rockets Milkshake (1/2)', type: 'per-sailing' },
      { id: 'dp-shake-2', label: '50% Off Johnny Rockets Milkshake (2/2)', type: 'per-sailing' },
      { id: 'dp-coffee-1', label: '50% Off Coffee (1/2)', type: 'per-sailing' },
      { id: 'dp-coffee-2', label: '50% Off Coffee (2/2)', type: 'per-sailing' },
      { id: 'dp-dining', label: 'BOGO Specialty Dining (Night 1 or 2)', type: 'per-sailing' },
      { id: 'dp-photo', label: '1 Free Photo', type: 'per-sailing' },
      { id: 'dp-internet', label: '2 Free Days Internet', type: 'per-sailing' },
      { id: 'dp-laundry', label: 'Free Wash & Fold Bag', type: 'per-sailing' },
      { id: 'dp-robes', label: 'Robes Requested', type: 'per-sailing' },
      { id: 'dp-casino', label: '$6 Casino FreePlay', type: 'per-sailing' },
      { id: 'dp-waters', label: '2 Welcome Waters Received', type: 'per-sailing' },
      { id: 'dp-bingo', label: '6 Free Bingo Cards', type: 'per-sailing' },
    ],
  },
  pinnacle: {
    id: 'pinnacle',
    name: 'pinnacle',
    displayName: 'Pinnacle',
    benefits: [
      { id: 'pin-drinks', label: 'Daily Drink Vouchers', type: 'daily', quantity: 6 },
      { id: 'pin-shake-1', label: '50% Off Johnny Rockets Milkshake (1/2)', type: 'per-sailing' },
      { id: 'pin-shake-2', label: '50% Off Johnny Rockets Milkshake (2/2)', type: 'per-sailing' },
      { id: 'pin-coffee-1', label: '50% Off Coffee (1/2)', type: 'per-sailing' },
      { id: 'pin-coffee-2', label: '50% Off Coffee (2/2)', type: 'per-sailing' },
      { id: 'pin-dining', label: 'BOGO Specialty Dining (Night 1 or 2)', type: 'per-sailing' },
      { id: 'pin-photo', label: '1 Free Photo', type: 'per-sailing' },
      { id: 'pin-internet', label: 'Free Internet (Unlimited)', type: 'per-sailing' },
      { id: 'pin-laundry', label: 'Free Wash & Fold Bag', type: 'per-sailing' },
      { id: 'pin-robes', label: 'Robes Requested', type: 'per-sailing' },
      { id: 'pin-casino', label: '$6 Casino FreePlay', type: 'per-sailing' },
      { id: 'pin-waters', label: '2 Welcome Waters Received', type: 'per-sailing' },
      { id: 'pin-bingo', label: '6 Free Bingo Cards', type: 'per-sailing' },
    ],
  },
};
